name: asset
version: 0.2.0
usage: Assemble assets into a single template file
description: |-
    This plugin allows users to assemble assets before doing `helm install` or `upgrade`.
ignoreFlags: false
useTunnel: true
command: "$HELM_PLUGIN_DIR/bin/helm-plugin-asset"
